package com.fahim.chesstimer.ui.theme

import androidx.compose.ui.graphics.Color

// ===========================================
// Grandmaster's Study - Warm, premium, refined
// ===========================================

// Light
val GmPrimaryLight = Color(0xFFB8860B)
val GmOnPrimaryLight = Color(0xFFFFFFFF)
val GmPrimaryContainerLight = Color(0xFFFFDEA1)
val GmOnPrimaryContainerLight = Color(0xFF281900)
val GmSecondaryLight = Color(0xFF6F5B40)
val GmOnSecondaryLight = Color(0xFFFFFFFF)
val GmSecondaryContainerLight = Color(0xFFFBDEBC)
val GmOnSecondaryContainerLight = Color(0xFF271904)
val GmTertiaryLight = Color(0xFF4E6545)
val GmOnTertiaryLight = Color(0xFFFFFFFF)
val GmTertiaryContainerLight = Color(0xFFD0EBC2)
val GmOnTertiaryContainerLight = Color(0xFF0C2007)
val GmBackgroundLight = Color(0xFFFFF8F0)
val GmOnBackgroundLight = Color(0xFF1F1B13)
val GmSurfaceLight = Color(0xFFFFF8F3)
val GmOnSurfaceLight = Color(0xFF1F1B13)
val GmSurfaceVariantLight = Color(0xFFF0E0C8)
val GmOnSurfaceVariantLight = Color(0xFF4F4539)
val GmOutlineLight = Color(0xFF817567)
val GmOutlineVariantLight = Color(0xFFD3C4B0)
val GmErrorLight = Color(0xFFC62828)
val GmOnErrorLight = Color(0xFFFFFFFF)

// Dark
val GmPrimaryDark = Color(0xFFD4A84B)
val GmOnPrimaryDark = Color(0xFF422D00)
val GmPrimaryContainerDark = Color(0xFF5F4200)
val GmOnPrimaryContainerDark = Color(0xFFFFDEA1)
val GmSecondaryDark = Color(0xFFDDC2A1)
val GmOnSecondaryDark = Color(0xFF3E2E16)
val GmSecondaryContainerDark = Color(0xFF57442A)
val GmOnSecondaryContainerDark = Color(0xFFFBDEBC)
val GmTertiaryDark = Color(0xFFB3D1A5)
val GmOnTertiaryDark = Color(0xFF20371A)
val GmTertiaryContainerDark = Color(0xFF374E2F)
val GmOnTertiaryContainerDark = Color(0xFFD0EBC2)
val GmBackgroundDark = Color(0xFF16120C)
val GmOnBackgroundDark = Color(0xFFF0E1CC)
val GmSurfaceDark = Color(0xFF16120C)
val GmOnSurfaceDark = Color(0xFFF0E1CC)
val GmSurfaceVariantDark = Color(0xFF4F4539)
val GmOnSurfaceVariantDark = Color(0xFFD3C4B0)
val GmOutlineDark = Color(0xFF9C8E7C)
val GmOutlineVariantDark = Color(0xFF4F4539)
val GmErrorDark = Color(0xFFEF5350)
val GmOnErrorDark = Color(0xFF690005)

// Grandmaster extended
val GmWhitePlayerLight = Color(0xFFFFF8F0)
val GmWhitePlayerTextLight = Color(0xFF2C1810)
val GmBlackPlayerLight = Color(0xFF3E2723)
val GmBlackPlayerTextLight = Color(0xFFFFF8F0)
val GmWhitePlayerDark = Color(0xFFF5E6C8)
val GmWhitePlayerTextDark = Color(0xFF1A1410)
val GmBlackPlayerDark = Color(0xFF1A1410)
val GmBlackPlayerTextDark = Color(0xFFF5E6C8)
val GmActiveAccent = Color(0xFFD4A84B)
val GmControlBarDark = Color(0xFF2A221C)
val GmControlBarLight = Color(0xFFFFF3E0)
val GmControlBarContentDark = Color(0xFFD4A84B)
val GmControlBarContentLight = Color(0xFFB8860B)

// ===========================================
// Blitz Arena - Sharp, competitive, electric
// ===========================================

// Light
val BzPrimaryLight = Color(0xFF0D47A1)
val BzOnPrimaryLight = Color(0xFFFFFFFF)
val BzPrimaryContainerLight = Color(0xFFD4E3FF)
val BzOnPrimaryContainerLight = Color(0xFF001C3A)
val BzSecondaryLight = Color(0xFFBF360C)
val BzOnSecondaryLight = Color(0xFFFFFFFF)
val BzSecondaryContainerLight = Color(0xFFFFDBD1)
val BzOnSecondaryContainerLight = Color(0xFF3B0900)
val BzTertiaryLight = Color(0xFF6750A4)
val BzOnTertiaryLight = Color(0xFFFFFFFF)
val BzTertiaryContainerLight = Color(0xFFEADDFF)
val BzOnTertiaryContainerLight = Color(0xFF21005D)
val BzBackgroundLight = Color(0xFFF5F5FA)
val BzOnBackgroundLight = Color(0xFF1A1B2E)
val BzSurfaceLight = Color(0xFFFCFCFF)
val BzOnSurfaceLight = Color(0xFF1A1B2E)
val BzSurfaceVariantLight = Color(0xFFE0E2EC)
val BzOnSurfaceVariantLight = Color(0xFF44474E)
val BzOutlineLight = Color(0xFF74777F)
val BzOutlineVariantLight = Color(0xFFC4C6D0)
val BzErrorLight = Color(0xFFD50000)
val BzOnErrorLight = Color(0xFFFFFFFF)

// Dark
val BzPrimaryDark = Color(0xFF00E5FF)
val BzOnPrimaryDark = Color(0xFF00344D)
val BzPrimaryContainerDark = Color(0xFF004D6F)
val BzOnPrimaryContainerDark = Color(0xFFB3F5FF)
val BzSecondaryDark = Color(0xFFFF8A65)
val BzOnSecondaryDark = Color(0xFF5C1900)
val BzSecondaryContainerDark = Color(0xFF7C2D12)
val BzOnSecondaryContainerDark = Color(0xFFFFDBD1)
val BzTertiaryDark = Color(0xFFCFBCFF)
val BzOnTertiaryDark = Color(0xFF381E72)
val BzTertiaryContainerDark = Color(0xFF4F378B)
val BzOnTertiaryContainerDark = Color(0xFFEADDFF)
val BzBackgroundDark = Color(0xFF0A0B14)
val BzOnBackgroundDark = Color(0xFFE2E2F0)
val BzSurfaceDark = Color(0xFF0A0B14)
val BzOnSurfaceDark = Color(0xFFE2E2F0)
val BzSurfaceVariantDark = Color(0xFF44474E)
val BzOnSurfaceVariantDark = Color(0xFFC4C6D0)
val BzOutlineDark = Color(0xFF8E9099)
val BzOutlineVariantDark = Color(0xFF44474E)
val BzErrorDark = Color(0xFFFF1744)
val BzOnErrorDark = Color(0xFF690005)

// Blitz extended
val BzWhitePlayerLight = Color(0xFFFFFFFF)
val BzWhitePlayerTextLight = Color(0xFF1A1B2E)
val BzBlackPlayerLight = Color(0xFF1A1B2E)
val BzBlackPlayerTextLight = Color(0xFFFFFFFF)
val BzWhitePlayerDark = Color(0xFFD8DAE6)
val BzWhitePlayerTextDark = Color(0xFF0A0B14)
val BzBlackPlayerDark = Color(0xFF0A0B14)
val BzBlackPlayerTextDark = Color(0xFFE2E2F0)
val BzActiveAccent = Color(0xFF00E5FF)
val BzControlBarDark = Color(0xFF14141F)
val BzControlBarLight = Color(0xFFECEDF4)
val BzControlBarContentDark = Color(0xFF00E5FF)
val BzControlBarContentLight = Color(0xFF0D47A1)

// Shared
val LowTimeWarning = Color(0xFFFF1744)
